name: Test & Lint

on:
  push:
    branches-ignore: [ master, main ]

jobs:
  commitlint:
    name: Lint commits
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: 15
          # We must indicate the Github Package Registry, as our config packages
          # are there (and also NPM). Frustratingly, NPM prefers the GPR over
          # NPM - even when we indicate that we want to pull from NPM instead of
          # the GPR.
          registry-url: https://npm.pkg.github.com

      - run: npm ci
        env:
          # Provide a "password" to GPR so that we can pull our packages.
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: npm-error-log
          path: /home/runner/.npm/_logs

      - run: npx commitlint --from HEAD~1 --to HEAD --verbose

  eslint:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 15
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci

      - run: npx eslint .

  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 15
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci

      - run: npm run test