name: Test & Lint

on:
  push:
    branches-ignore: [ master ]

jobs:
  commitlint:
    name: Lint commits
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: 15

      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: npm-install-log
          path: /home/runner/.npm/_logs

      - run: npx commitlint --from HEAD~1 --to HEAD --verbose

  eslint:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 15

      - run: npm ci

      - run: npm ci

      - run: npx eslint .

  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 15

      - run: npm ci

      - run: npm run test