name: Test & Lint

on:
  push:
    branches-ignore: [ master, main ]

jobs:
  commitlint:
    name: Lint commits
    runs-on: ubuntu-latest

    steps:
      - uses: action/checkout@v2
        with:
          fetch-depth: 0

      - uses: action/setup-node@v2
        with:
          node-version: 15

      - run: npm ci

      - run: npx commitlint --from HEAD~1 --to HEAD --verbose

  eslint:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - uses: action/checkout@v2

      - uses: action/setup-node@v2
        with:
          node-version: 15

      - run: npm ci

      - run: npx eslint .

  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: action/checkout@v2

      - uses: action/setup-node@v2
        with:
          node-version: 15

      - run: npm ci

      - run: npm run test